//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductShop.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Product
    {
        public int ID { get; set; }
        public int Country { get; set; }
        public int Product { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
